Ios module
trackier/react-native-sdk pull request #11
Opened 2021-04-30 09:39 UTC by prak24oct

IOS Module Implemented

2021-04-30 10:22 UTC, Hemant-Mann requested changes
do the changes mentioned in the comments and remove the files
- example/package-lock.json
- package-lock.json

2021-04-30 10:22 UTC, Hemant-Mann commented on index.js
> +    console.log(module_trackier);
remove console

2021-04-30 10:22 UTC, Hemant-Mann commented on index.js
> +  //  if (typeof key !== 'string' || typeof value !== 'string') {
remove comment

2021-04-30 10:22 UTC, Hemant-Mann commented on ios/RNTrackierSDK.swift
> +        sleep(1)
remove sleep

2021-04-30 10:22 UTC, Hemant-Mann commented on ios/RNTrackierSDK.swift
> +      var eventId: String?
```suggestion
      var eventId: String
```

2021-04-30 10:22 UTC, Hemant-Mann commented on ios/RNTrackierSDK.swift
> +      for (key, value) in ev! {
should be wrapped around if ev != nil

2021-04-30 10:22 UTC, Hemant-Mann commented on ios/RNTrackierSDK.swift
> +      event.setRevenue(revenue: Float64(revenue!.floatValue), currency: currency!)
should check if revenue != nil and currency != nil

2021-04-30 10:22 UTC, Hemant-Mann commented on ios/RNTrackierSDK.swift
> +      for (key, value) in ev! {
if ev != nil

2021-04-30 10:40 UTC, prak24oct commented on index.js
> +  //  if (typeof key !== 'string' || typeof value !== 'string') {
value can be any , for that we have to remove  "typeof value !== 'string'" check

2021-04-30 10:43 UTC, prak24oct commented on ios/RNTrackierSDK.swift
> +      for (key, value) in ev! {
it will check in line no 55 if it will be nil , will then send "{}" instead.

2021-04-30 10:44 UTC, prak24oct commented on ios/RNTrackierSDK.swift
> +      for (key, value) in ev! {
Already applied check above

2021-04-30 11:47 UTC, Hemant-Mann commented on ios/RNTrackierSDK.swift
> +        let currency: String = dict["currency"] as? String ?? ""
indentation fix @prak24oct

2021-04-30 12:54 UTC, Hemant-Mann requested changes

2021-04-30 12:54 UTC, Hemant-Mann commented on index.js
> +    if(typeof eventId !== 'string') {
```suggestion
    if (typeof eventId !== 'string') {
```

2021-04-30 12:54 UTC, Hemant-Mann commented on example/App.js
> +    var trackierEvent = new TrackierEvent(23);
discard this change

2021-05-03 07:03 UTC, prak24oct commented on ios/RNTrackierSDK.swift
> +        let currency: String = dict["currency"] as? String ?? ""
fixed but not showing resolved here

2021-05-03 07:05 UTC, Hemant-Mann commented on ios/RNTrackierSDK.swift
> +        let currency: String = dict["currency"] as? String ?? ""
aisa nahi hota bhai fix karo isse

2021-05-03 07:06 UTC, Hemant-Mann commented on ios/RNTrackierSDK.swift
> +extension String {
is it necessary to use extension for 1 line of code? @prak24oct

2021-05-03 07:15 UTC, Hemant-Mann requested changes
fix the syntax

2021-05-04 08:02 UTC, Hemant-Mann approved these changes

2021-05-04 08:02 UTC, merged