feat-deferred-deeplinking-support
trackier/react-native-sdk pull request #26
Opened 2022-10-03 07:25 UTC by IloveJavaa

Deferred deeplinking support in android
Link - https://app.asana.com/0/0/1203084579645630/f

2022-10-03 07:38 UTC, Hemant-Mann requested changes

2022-10-03 07:38 UTC, Hemant-Mann commented on android/src/main/java/com/reactlibrary/TrackierSDK.java
> +	DeepLinkListener deepLinkListener = new DeepLinkListener() {
don't make it a class property as mentioned before, move this code to line no 45 below

2022-10-03 07:38 UTC, Hemant-Mann commented on android/src/main/java/com/reactlibrary/TrackierSDK.java
> +		sdkConfig.setDeepLinkListener(deepLinkListener);
this code should be wrapped around an if check

2022-10-03 07:50 UTC, IloveJavaa commented on android/src/main/java/com/reactlibrary/TrackierSDK.java
> +	DeepLinkListener deepLinkListener = new DeepLinkListener() {
Done

2022-10-04 06:01 UTC, Hemant-Mann approved these changes

2022-10-04 06:01 UTC, merged