Update deferred deeplinking iOS
trackier/react-native-sdk pull request #34
Opened 2023-04-04 10:39 UTC by IloveJavaa

Asana - https://app.asana.com/0/0/1204212631804152/f

2023-04-04 12:02 UTC, Hemant-Mann commented on index.js
> +	this.appSecret = {}
let's add 2 props instead of 1 @IloveJavaa 
this.secretId = 
this.secretKey =

2023-04-04 12:02 UTC, Hemant-Mann commented on index.js
> +	this.appSecret = {}
also we'll need to update the index.d.ts file

2023-04-04 12:03 UTC, Hemant-Mann commented on ios/RNTrackierSDK.swift
> -	 @objc func setAppSecret(_ dict: NSDictionary) -> Void {
if we are deprecating this function then let's also remove the function from TrackierSDK

2023-04-05 07:27 UTC, IloveJavaa commented on index.js
> +	this.appSecret = {}
All changes done

2023-04-05 07:41 UTC, IloveJavaa commented on ios/RNTrackierSDK.swift
> +		if(deeplinking == true){
done

2023-04-05 07:41 UTC, IloveJavaa commented on ios/RNTrackierSDK.swift
> -	 @objc func setAppSecret(_ dict: NSDictionary) -> Void {
ok

2023-04-06 05:48 UTC, Hemant-Mann commented on index.js
> +	this.secretId = {}
```suggestion
	this.secretId = '';
```

2023-04-06 05:48 UTC, Hemant-Mann commented on index.js
> +	this.secretKey = {}
```suggestion
	this.secretKey = '';
```

2023-04-06 05:49 UTC, Hemant-Mann requested changes

2023-04-06 05:49 UTC, Hemant-Mann commented on ios/RNTrackierSDK.swift
> +		let appSecret:Dictionary<String,Any> = dict["appSecret"] as? Dictionary<String,Any> ?? [:]
this is a string value

2023-04-06 05:49 UTC, Hemant-Mann commented on ios/RNTrackierSDK.swift
> +		let appSecret:Dictionary<String,Any> = dict["appSecret"] as? Dictionary<String,Any> ?? [:]
plz fix it

2023-04-06 06:10 UTC, IloveJavaa commented on ios/RNTrackierSDK.swift
> +		let appSecret:Dictionary<String,Any> = dict["appSecret"] as? Dictionary<String,Any> ?? [:]
done

2023-04-06 06:10 UTC, IloveJavaa commented on index.js
> +	this.secretKey = {}
done

2023-04-06 06:11 UTC, IloveJavaa commented on index.js
> +	this.secretId = {}
done

2023-04-06 08:54 UTC, Hemant-Mann commented on index.js
> +TrackierConfig.prototype.setAppSecret = function(key, value){
```suggestion
TrackierConfig.prototype.setAppSecret = function(key, value) {
```

2023-04-08 10:48 UTC, Hemant-Mann commented on index.js
> +	this.secretId = ''
```suggestion
	this.secretId = '';
```

2023-04-08 10:48 UTC, Hemant-Mann commented on index.js
> +	this.secretKey = ''
```suggestion
	this.secretKey = '';
```

2023-04-08 10:51 UTC, Hemant-Mann commented on ios/RNTrackierSDK.swift
> +		if((deeplinking) != nil) {
```suggestion
		if (deeplinking != nil) {
```

2023-04-08 10:52 UTC, Hemant-Mann approved these changes

2023-04-28 13:09 UTC, Hemant-Mann commented on index.js
> +	if (Platform.OS === "android") {
if else block can be removed because code is same

2023-04-28 14:58 UTC, Hemant-Mann approved these changes

2023-04-28 14:58 UTC, merged