Update sdk versions
trackier/react-native-sdk pull request #42
Opened 2024-08-12 13:20 UTC by IloveJavaa

Asana Link - https://app.asana.com/0/1202373337684004/1208033610075600/f

2024-08-12 13:42 UTC, Hemant-Mann requested changes

2024-08-12 13:42 UTC, Hemant-Mann commented on android/src/main/java/com/reactrackier/TrackierSDK.java
> +			trackierEvent.couponCode = trackierEventMap.getString("productId");
Incorrect property assignment

2024-08-12 13:42 UTC, Hemant-Mann commented on android/src/main/java/com/reactrackier/TrackierUtil.java
> +		    return new HashMap<>();
Return result here instead of empty map we should work with whatever value we are having

2024-08-12 13:48 UTC, IloveJavaa commented on android/src/main/java/com/reactrackier/TrackierUtil.java
> +		    return new HashMap<>();
done

2024-08-12 13:48 UTC, IloveJavaa commented on android/src/main/java/com/reactrackier/TrackierSDK.java
> +			trackierEvent.couponCode = trackierEventMap.getString("productId");
done

2024-08-13 19:37 UTC, Hemant-Mann approved these changes

2024-08-13 19:37 UTC, merged